services:
  - type: web
    name: sebi-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py" # Change this if your entry is different
    runtime: python3
    rootDir: backend
